version: '3.9'

services:
    games-store-app:
        build: .
        ports:
            - "3000:3000"
        environment:
            - AUTH0_SECRET=${AUTH0_SECRET}
            - AUTH0_BASE_URL=${AUTH0_BASE_URL}
            - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
            - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
            - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
            - AUTH0_HOOK_SECRET=${AUTH0_HOOK_SECRET}
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        networks:
            - backend_games-store

networks:
    backend_games-store:
        external: true