version: '3.9'

services:
    games-store-postgres:
        image: postgres:latest
        ports:
            - 6432:6432
        volumes:
            - /var/lib/postgresql/data/
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=admin
            - POSTGRES_DB=games-store-db
            - DB_PORT=6432
            - PGDATA=/var/lib/postgresql/data/
        command: -p 6432

    games-store-api:
        build: .
        ports:
            - 4000:4000
        depends_on:
            - games-store-postgres
