version: '3.9'

services:
    games-store-postgres:
        image: postgres:latest
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - /var/lib/postgresql/data/
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - DB_PORT=${DB_PORT}
            - PGDATA=/var/lib/postgresql/data/
        command: -p ${DB_PORT}

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"

    games-store-api:
        build: .
        ports:
            - ${API_PORT}:${API_PORT}
        depends_on:
            - games-store-postgres
            - nginx
