version: '3.9'

services:
    games-store-postgres:
        image: postgres:latest
        restart: always
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - /var/lib/postgresql/data/
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - DB_PORT=${DB_PORT}
            - PGDATA=/var/lib/postgresql/data/
        command: -p ${DB_PORT}
        networks:
            - frontend_some-net

    nginx:
        restart: always
        build: ./nginx
        ports:
            - "80:80"
        networks:
            - frontend_some-net

    games-store-api:
        build: .
        ports:
            - ${API_PORT}:${API_PORT}
            - ${DB_STUDIO_PORT}:${DB_STUDIO_PORT}
        environment:
            - API_PORT=${API_PORT}
            - DATABASE_URL=${DATABASE_URL_DOCKER}
            - AUTH0_ISSUER_BASE_URL=${AUTH0_ISSUER_BASE_URL}
            - APP_AWS_ACCESS_KEY=${APP_AWS_ACCESS_KEY}
            - APP_AWS_SECRET_KEY=${APP_AWS_SECRET_KEY}
            - DB_STUDIO_PORT=${DB_STUDIO_PORT}
        depends_on:
            - games-store-postgres
            - nginx
        networks:
            - frontend_some-net
networks:
    frontend_some-net:
        external: true