name: Build
on:
  pull_request:
    paths:
      - 'frontend/**'
jobs:
  build:
    runs-on: self-hosted
    env:
      AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
      AUTH0_BASE_URL: ${{ secrets.AUTH0_BASE_URL }}
      AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      AUTH0_HOOK_SECRET: ${{ secrets.AUTH0_HOOK_SECRET }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
    steps:
      - uses: actions/checkout@v4
      - run: cd frontend && docker-compose build
