name: Check
on: pull_request
jobs:
  be:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: cd backend && docker-compose build && docker-compose up -d
  # fe:
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - run: npm i -g yarn
  #     - run: cd frontend && yarn
  #     - run: cd frontend && yarn lint
  #     - run: cd frontend && yarn build
